import os
import glob
import subprocess
from pathlib import Path
from mcp.server.fastmcp import FastMCP

# Initialize FastMCP Server
mcp = FastMCP("UE Crash Analyzer")

def find_cdb_exe() -> str:
    """Attempt to find cdb.exe in standard Windows Kits installation paths."""
    common_paths = [
        r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe",
        r"C:\Program Files\Windows Kits\10\Debuggers\x64\cdb.exe",
        r"C:\Program Files (x86)\Windows Kits\11\Debuggers\x64\cdb.exe"
    ]
    for p in common_paths:
        if os.path.exists(p):
            return p
    return "cdb.exe" # Fallback to PATH environment variable if not found

@mcp.tool()
def get_latest_ue_crash_log(project_dir: str = "", explicit_crash_dir: str = "") -> str:
    """
    Search for the latest Unreal Engine crash logs.
    If a specific crash directory is provided, it analyzes that directory.
    Otherwise, it searches in the Saved/Crashes directory of a project.
    
    Args:
        project_dir: The root directory of the Unreal Engine project (e.g. D:/MyGame). Can be empty if explicit_crash_dir is provided.
        explicit_crash_dir: Optional. The exact path to a crash folder (containing Diagnostics.txt and .log). If provided, it analyzes this specific folder instead of searching project_dir/Saved/Crashes.
    
    Returns:
        The content of Diagnostics.txt and the relevant log trace.
    """
    if explicit_crash_dir:
        crash_source_dir = Path(explicit_crash_dir)
        if not crash_source_dir.exists() or not crash_source_dir.is_dir():
            return f"Error: Explicit crash directory not found at {crash_source_dir}"
        latest_crash = crash_source_dir
    else:
        if not project_dir:
            return "Error: Either project_dir or explicit_crash_dir must be provided."
            
        crash_dir = Path(project_dir) / "Saved" / "Crashes"
        if not crash_dir.exists() or not crash_dir.is_dir():
            return f"Error: Crash directory not found at {crash_dir}"
        
        # Exclude files, only find folders
        crash_folders = [f for f in crash_dir.iterdir() if f.is_dir()]
        if not crash_folders:
            return f"Error: No crash folders found in {crash_dir}"
        
        # Sort folders by modification time (most recent first)
        crash_folders.sort(key=lambda x: x.stat().st_mtime, reverse=True)
        latest_crash = crash_folders[0]
    
    output = f"Found latest crash at: {latest_crash}\n"
    output += "=" * 50 + "\n\n"
    
    diag_file = latest_crash / "Diagnostics.txt"
    if diag_file.exists():
        output += "[Diagnostics.txt Content:]\n"
        with open(diag_file, "r", encoding="utf-8", errors="replace") as f:
            output += f.read()
    else:
        output += "No Diagnostics.txt found.\n"
        
    output += "\n" + ("=" * 50) + "\n\n"
    
    # Look for the project log file (.log)
    log_files = list(latest_crash.glob("*.log"))
    if log_files:
        output += f"[{log_files[0].name} Callstack Extract:]\n"
        # We read the last ~50KB for the stack trace to avoid memory overload on huge logs
        try:
            file_size = os.path.getsize(log_files[0])
            max_bytes = 50000 # 약 50KB (대략 500~1000줄 정도의 넉넉한 분량)
            
            with open(log_files[0], "r", encoding="utf-8", errors="replace") as f:
                if file_size > max_bytes:
                    f.seek(file_size - max_bytes)
                    f.readline() # 잘려진 첫 번째 불완전한 줄은 버림
                
                lines = f.readlines()
            
            error_idx = -1
            for i, line in enumerate(lines):
                if "Fatal error" in line or "Assertion failed" in line or "Unhandled Exception" in line:
                    error_idx = i
                    break
            
            if error_idx != -1: # Found an error line, extract from there
                start_l = max(0, error_idx - 10) # 에러 발생 10줄 전부터
                # 파일 끝부분만 가져왔으므로 끝까지 쭉 출력해도 안전함
                output += "".join(lines[start_l:]) 
            else:
                # 에러 키워드를 못 찾았더라도 마지막 100줄만 반환
                output += "".join(lines[-100:])
                
        except Exception as e:
            output += f"Error reading log file: {e}\n"
    else:
        output += "No .log files found in crash directory.\n"
        
    return output

@mcp.tool()
def analyze_ue_dump(dump_file_path: str, project_dir: str = "", team_symbol_server_path: str = "") -> str:
    """
    Analyzes a Windows minidump (.dmp) file generated by Unreal Engine using cdb.exe (Windows Debugger).
    
    Args:
        dump_file_path: Absolute path to the .dmp file to analyze.
        project_dir: Optional. The root directory of the local Unreal Engine project to map PDBs and executables (e.g. D:/MyGame).
        team_symbol_server_path: Optional. Path to a local folder or network share containing your team's archived PDBs and EXEs (e.g., Z:/Builds/Symbols). Can also be a standard symbol server URL (SRV*...).
        
    Returns:
        The text output containing the bugcheck analysis and call stack.
    """
    dump_path = Path(dump_file_path)
    if not dump_path.exists():
        return f"Error: Dump file not found at {dump_path}"
    
    cdb_path = find_cdb_exe()
    
    # We pass the commands to evaluate and quit
    # !analyze -v: Detailed dump analysis
    # q: Quit
    
    symbol_paths = []
    image_paths = []

    # 1. Add local project binaries if available
    if project_dir:
        proj_path = Path(project_dir)
        binaries_path = proj_path / "Binaries" / "Win64"
        if binaries_path.exists():
            symbol_paths.append(str(binaries_path))
            image_paths.append(str(binaries_path))
            
    # 2. Add team symbol server or network share
    if team_symbol_server_path:
        # Note: If passing a true symbol server like SRV*c:\symcache*\\server\symbols, 
        # cdb handles it natively when passed to -y
        symbol_paths.append(team_symbol_server_path)
        # Also add it to image paths in case EXEs/DLLs are stored there alongside PDBs
        image_paths.append(team_symbol_server_path)
        
    # Append collected paths to the command
    if image_paths:
        command.extend(["-i", ";".join(image_paths)])
    if symbol_paths:
        command.extend(["-y", ";".join(symbol_paths)])

    command.extend(["-z", str(dump_path), "-c", "!analyze -v; q"])
    
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=120  # Give it 2 minutes max
        )
        
        output = result.stdout
        if result.stderr:
            output += "\n\nStandard Error:\n" + result.stderr
            
        return output
    except FileNotFoundError:
        return "Error: cdb.exe could not be found. Please ensure Windows SDK Debugging Tools are installed."
    except subprocess.TimeoutExpired:
        return "Error: Analysis timed out after 120 seconds."
    except Exception as e:
        return f"Error executing debugger: {e}"

if __name__ == "__main__":
    mcp.run()
